build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - tests/unit/*
    - tests/_support/*
    - tests/_data/*
  dependency_paths:
    - src/Utility/

tools:
  external_code_coverage: true

checks:
  php: true
