build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  dependency_paths:
    - tests/*
    - src/Legacy/

tools:
  external_code_coverage: true

checks:
  php: true
