language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction --no-progress --no-suggest --no-scripts"

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env:
        - CS_CHECK=true
        - TEST_COVERAGE=true
        - ANALYSIS=true

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0; fi

install:
  - travis_retry composer install --ignore-platform-reqs $COMPOSER_ARGS
  - stty cols 120 && composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage; else composer test; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check; fi
  - if [[ $ANALYSIS == 'true' ]]; then composer psalm; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then
    wget https://scrutinizer-ci.com/ocular.phar;
    php ocular.phar code-coverage:upload --format=php-clover clover.xml;
    fi

notifications:
  email: false
