name: tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.2.x'
          - '7.3.x'

    steps:
      - uses: actions/checkout@v1

      - name: Install PHP extensions
        run: sudo apt-get -y install php-mbstring php-intl

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Check syntax of PHP files
        run: composer lint

      - name: Check coding style
        run: composer cs-check

      - name: Run test suite
        run: composer test-coverage

      - name: Upload coverage results
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
