name: Testing johncms/system
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        php-versions: ['7.2', '7.3']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          coverage: xdebug #optional

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-interaction

      - name: Check coding style
        run: composer cs-check

      - name: Run test suite
        run: composer test-coverage

      - name: Upload coverage results
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover clover.xml
